### ISSUE TITLE
Console Spam on Latest MMOCore Snapshot 

### ISSUE THREAD

**Issue by Dynamite99** [mmopluginteam/mmocore#110]
**Please include a `latest.log` uploaded to [pastebin.com](https://pastebin.com) here:**
https://pastebin.com/Srm1rTCt

**Describe the bug**
Console Spam. Occurs randomly and spams constantly.

**Server info:**
 - Paper 1.16.1 #111
 - MMOLib 1.2.5 / MMOCore 1.4.2-SNAPSHOT / MMOItems 5.5.4

**Comment by jacobmepstein** [comment]
This bug is known, and will be fixed in an upcoming release.

**Comment by jacobmepstein** [comment]
Should be fixed in MMOItems 5.5.4 Build 3370 and MMOCore 1.4.3.
