### ISSUE TITLE
NPC Fishing Error

### ISSUE THREAD

**Issue by Maitlans** [mmopluginteam/mmocore#117]
Log: https://pastebin.com/Pi2SUYQ8

**Describe the bug**
I'm using the plugin NPCDestinations to create immersive NPCs through out the world and whenever the NPC catches a fish the console will output an error. This was not happening in previous versions of mmocore.

**To Reproduce**
1. Install NPCDestinations
2. Create an NPC fishing.
3. Wait for him to catch a fish

**Server info:**
 - git-Paper-101 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
 - Plugin Version: MMOCore v1.4.2-SNAPSHOT
 - Potential plugins linked to the issue: NPCDestinations

**Comment by Ehhthan** [comment]
This will be fixed in the newest dev build.
