### ISSUE TITLE
Event Trigger Per X Level / On Level X

### ISSUE THREAD

**Issue by ZephyalGates** [mmopluginteam/mmocore#125]
**Is your feature request related to a problem? Please describe.**
No, but it will be very handy for some situations.

**Describe the solution you'd like**
For example, every 10 levels in mining, 1 skill-point is given; On level 50 in mining, a permission node is set to true.

**Describe alternatives you've considered**
A clunkier way to do this is give 0.1 skill-point on mining level-up, which I'll have to multiply it by 10 to make it an integer.(give 10 skill-points on main level-up, 1 skill-point on mining level-up)

**Additional context**
/

**Comment by Joshinn-mc** [comment]
@ZephyalGates 

level-up-mining-10:

level-up-mining-20:

Etc

These already exist.

**Comment by jacobmepstein** [comment]
The plugin MMOExtended adds this functionality: https://github.com/Ehhthan/mmoextended/wiki/Triggers

**Comment by Ehhthan** [comment]
This will be added in a new dev build once build bot is working.

**Comment by ZephyalGates** [comment]
Thanks for the replies.
