### ISSUE TITLE
Suggestion - Conditions for skills

### ISSUE THREAD

**Issue by drAkeEngine** [mmopluginteam/mmocore#20]
I am pleased to see this great work and the development of the complement. I congratulate the development team.

I used to use the SkillAPI plugin
and there is something that I would like to adapt the conditions to the skills, such as necessary attributes, level of a specific skill etc etc.

This would give incredible versatility and in conjunction with Mythicmobs skills would be great.

(Sorry for my bad english)

**Comment by Joshinn-mc** [comment]
Cleaning up old tickets... this can be done using mythicmobs. they have a complex conditions system. If you're looking for something more in depth - will have to wait for the champions merge.
