### ISSUE TITLE
BUG - Custom skills works weird (even tutorial spell)

### ISSUE THREAD

**Issue by CalamityGreen** [mmopluginteam/mmocore#27]
Hello, have a nice day. The problem is pretty complex as you see. We are using one of the last Mythic Mobs 4.9.0 snapshot (same with the stable 4.9.0 premium), MMOLibs 1.8.0 and MMOCore 1.2.4. PlaceholderAPI-2.10.4. Server version is 1.15.2

Mobs from MM works as well, the same are their skills and other features.
Some spells coded in the MMOC (ice spikes for ex) wont work too, but most of them does.

Example provided here: [https://github.com/Indyuce/mmocore/wiki/Skills-Folder](https://github.com/Indyuce/mmocore/wiki/Skills-Folder) seems to visually work, but can not damage anything (no console error, skill just can't hit anything and goes trought blocks and entities) with or without placeholders from MMOC. There is no "hnp=true " in projectile mechanic which I fixed. But problem is next.

When I'm using [this spell](https://pastebin.com/qWpcsWmX) (spell which summons another direct spell huh) it succesfully damages target. But again, when I'm trying to add placeholder <mmocore.skill.meteor.damage> to damage values, damage is gone and console say [this](https://pastebin.com/MqpaBfAF).

# Another example:

[Skill](https://pastebin.com/ZZMyVpKJ) (tutorial skill but + with hnp) - [Console placeholders errors](https://pastebin.com/12zkG5SS)

Also if you cast sorta of homing skills (like a fire storm) there is no effect if you miss, but mana cost and recharge time are spended. Sry for bad english.

**Comment by Indyuce** [comment]
The `<mmocore.skill....>` placeholder has to exactly match (case sensitive) the MythicMobs skill internal name which would be `Meteor`. You may give `<mmocore.skill.Meteor.damage>` a try.

**Comment by yerktoyn** [comment]
Yes, the problem is present. We spent a lot of time, but failed to get the modifier to work. The same error in the logs

We use the same name as in the skill (with case sensitive)

**Comment by AshenGaming** [comment]
Hi there! We're in the process of cleaning up the Github for MMOCore, and as such closing old issues. If you are still experiencing this issue, please open a new issue using the Issue Template format provided as opposed to re-opening this one.
