### ISSUE TITLE
[Question] Check if a player is an ally or not

### ISSUE THREAD

**Issue by Tiplish** [mmopluginteam/mmocore#37]
Hi,

For a spell, i've to check if the player is targetable (not is the same team or invulnerable).

If you could hit him, do damage. If you can't hit him, heal him. 

Haven't see if it's possible with mmocore/mythicmob compatibility and custom spells.

Thanks.

**Comment by Indyuce** [comment]
Get the player's PlayerData using `PlayerData.get(Player)`

Check if the player has a party using `playerData.hasParty()`, if so check if the target is in the party using `playerData.getParty().getMembers().has(targetPlayerData)`

Check if a player has a guild using `playerData.inGuild()` and check if the target is in that guild using `playerData.getGuild().getMembers().has(targetUuid)`

**Comment by Tiplish** [comment]
Hi thanks for the answer.

I suppose that mythicmobs spells doesn't include this ?
For the moment, i try to make mythicmobs spells imported in MMOcore before choosing hard coding spells in java :)

**Comment by Tiplish** [comment]
Hi,

Any answer ? I'm a bit stuck for the moment. I would know if i have to start hard coding spells and how or if i could just stay focus on Mythicmobs.

**Comment by Indyuce** [comment]
There is no way to check that with MythicMobs atm

**Comment by Tiplish** [comment]
And if i would like to hard code the spells like you did. How i could do this ? I've understand the playerData.hasParty() part but i don't know how to start if i would make custom spells in java and your API.

**Comment by Indyuce** [comment]
Check out the two classes I just uploaded in the source code tab. You need to create a class which extends `Skill` (make it implement Listener if you need to, don't register its events, MMOCore does it for you), and register it using
`MMOCore.plugin.skillManager.register(yourSkill)`
