### ISSUE TITLE
[Suggestion/Issue] Hand option in Restrictions.yml

### ISSUE THREAD

**Issue by RocheErwan** [mmopluginteam/mmocore#45]
Hi! MMOCore and MMOItem are wonderful tools, no regrets for having chosen them!

It would be really cool if we could open the restrictions at the hands of the players. (no idea if it's possible).
Also I would like to notify you that the regeneration of the blocks is canceled when the server is restarted. It's a bit worry during maintenance ^^

Big thx!

**Comment by Indyuce** [comment]
Hey, I believe using AIR works. The block regen issue will be fixed in the next spigot release
Thanks for your support 👍
