### ISSUE TITLE
Editing the levels.txt or creating a custom XP curve breaks the plugin on the 1.3 Dev Build.

### ISSUE THREAD

**Issue by INsynth** [mmopluginteam/mmocore#46]
[levels.txt](https://github.com/Indyuce/mmocore/files/4569556/levels.txt)

Have tried

- Editing the file
- Making a new xp curve with a different name
- Editing the old xp curve, but with the same number of entries

All of these so far cause the plugin to crash. Editing the XP curve but keeping the same number of entries seems to keep it running, but the changes are not reflected.

**Comment by Indyuce** [comment]
There's a space somewhere in your txt file that prevents MMOCore from reading the exp integer. This type of issue should not make the plugin crash in the latest versions bc of how exp curves are now handled
