### ISSUE TITLE
Stacking boosters when it's the same type

### ISSUE THREAD

**Issue by dellise26** [mmopluginteam/mmocore#47]
Currently, when a booster is given to a player, a new booster is added to the booster queue and the counter reduce at the same time, it would be awesome if the boosters could stack themself when it's the same type, for example : a player as already a main booster of 300 sec, and i add a booster of 300 type main, then the result won't be 2 boosters of main at the same time, but one booster of 600 sec type main.
I hope i was clear enough ( i think so ) and hope for it in the future improvements, good luck and awesome plugin :) # #

**Comment by Indyuce** [comment]
Basically instead of displaying multiple boosters, just increase the length of a booster if any of the same time already exists. It might be better for display indeed, will be added asap
