### ISSUE TITLE
BUG - Placeholder in 1.15.2

### ISSUE THREAD

**Issue by RenaudRl** [mmopluginteam/mmocore#48]
Version Paperspigot lastbuild 1.15.2 

Hello, i try the last update "5.4" and the placeholder for:
- life (number = correct number - base number)
- Attack speed (very buggy) 
- Attack damage (very buggy) 
- Speed movement (-0.2 related to correct number)
other than that, a very good plugin, good work :)
Thank,

**Comment by AshenGaming** [comment]
Hi there! We're in the process of cleaning up the Github for MMOCore, and as such closing old issues. If you are still experiencing this issue, please open a new issue using the Issue Template format provided as opposed to re-opening this one.
