### ISSUE TITLE
[NPE] PlayerItemHeldEvent - 1.15.2 | MMOCore 1.3

### ISSUE THREAD

**Issue by Kalorte** [mmopluginteam/mmocore#51]
Hey,

I have a NPE when using Mythicmobs skill with MMOCore. 
The skills works well (Only Skills, not _all_ the conditions inside the skills)
But there is always (everytime I do a skill) a NPE:

https://gyazo.com/6f3bbd795d45d2fb53dbf632852a345c

Using:
- Paper 245 (1.15.2)
- MMOCore 1.3 Release
- MythicMobs 4.9.1 Dev #3292

**Comment by AshenGaming** [comment]
Hi there! We're in the process of cleaning up the Github for MMOCore, and as such closing old issues. If you are still experiencing this issue, please open a new issue using the Issue Template format provided as opposed to re-opening this one.
