### ISSUE TITLE
[Bug] Leveling is showing a level 1 higher than the level I actually get

### ISSUE THREAD

**Issue by iMxAndyy** [mmopluginteam/mmocore#53]
When I level up a profession, It gives me a message in chat to tell me what level I have achieved. although the message is always 1 level higher than the level I actually got.

Screenshot attached showing the chat message and the level I actually am post leveling up

![xV8nXKE3SGeRo4shdZPS3g](https://user-images.githubusercontent.com/6192836/81247161-2fdbd000-9011-11ea-8acc-fe4f35f092bb.png)

**Comment by AshenGaming** [comment]
Hi there! We're in the process of cleaning up the Github for MMOCore, and as such closing old issues. If you are still experiencing this issue, please open a new issue using the Issue Template format provided as opposed to re-opening this one.
