### ISSUE TITLE
[Bug] Class level up trigger not working

### ISSUE THREAD

**Issue by iMxAndyy** [mmopluginteam/mmocore#54]
triggers:
    level-up-mining-2:
    - 'command{format="mmocore admin exp give %player% main 885"}'
    level-up-woodcutting-2:
    - 'command{format="mmocore admin exp give %player% main 885"}'
    level-up-hunting-2:
    - 'command{format="mmocore admin exp give %player% main 885"}'

This is a snippet from my class config. 
My aim is to make it so when you level up a profession you gain a specific amount of xp depending on your level, that is determined by some formula. 
As I can't do this in the plugin directly since it only allows for a base xp amount to be sent and i can't make that scale up exponentially I'm having to do it via triggers that add the specific amount of xp to main when the user level's up a profession. 

However this doesn't appear to work as expected. I'm not certain if this is a bug or if i'm doing something wrong but i asked in discord support about it and was told it looked right. so I'm raising it as a bug. If I'm just doing it wrong please let me know.

**Comment by AshenGaming** [comment]
Hi there! We're in the process of cleaning up the Github for MMOCore, and as such closing old issues. If you are still experiencing this issue, please open a new issue using the Issue Template format provided as opposed to re-opening this one.
