### ISSUE TITLE
Something wrong with Attack Speed

### ISSUE THREAD

**Issue by Darwin1546** [mmopluginteam/mmocore#55]
Looks like Attack Speed is bugged after 1.3
![изображение](https://user-images.githubusercontent.com/63585283/81415246-c37ce000-917a-11ea-9b20-a23cdf442ccc.png)
![изображение](https://user-images.githubusercontent.com/63585283/81415302-d98aa080-917a-11ea-9ccf-cb50bbc053ff.png)

If i trying to remove it, it's coming back after server restart.
![изображение](https://user-images.githubusercontent.com/63585283/81415366-f1fabb00-917a-11ea-94c3-ebd7974cbdb3.png)

Similar report from another player:
![изображение](https://user-images.githubusercontent.com/63585283/81415797-7baa8880-917b-11ea-8415-dfa29b60bb6a.png)

**Comment by AshenGaming** [comment]
Hi there! We're in the process of cleaning up the Github for MMOCore, and as such closing old issues. If you are still experiencing this issue, please open a new issue using the Issue Template format provided as opposed to re-opening this one.
