### ISSUE TITLE
Level 1 player's have 0 hearts of life when joining the server

### ISSUE THREAD

**Issue by PierreBouchet** [mmopluginteam/mmocore#57]
Sometimes when a player joins the serv we have this error : 
https://pastebin.com/Hm1jzXpZ
The player died as his life is 0 instead of 10 (as it is defined in my main classe config file).
I noticed that some players don't have the problems. It appears that the only victims are level 1 players. 
After that the player is like invisible on the server, we don't see him, we can't interact. 
The only way to solve the problem is to add him to the main classe with a command. 
Thanks by advance

**Comment by AshenGaming** [comment]
Hi there! We're in the process of cleaning up the Github for MMOCore, and as such closing old issues. If you are still experiencing this issue, please open a new issue using the Issue Template format provided as opposed to re-opening this one.
