### ISSUE TITLE
Armor Weight and other config inconsistencies

### ISSUE THREAD

**Issue by Darwin1546** [mmopluginteam/mmocore#60]
Wiki says that i can set Armor Weight in main config, but there is no such option.

And how to use mmocore enchantsments? There is list of enchantsments on wiki [page](https://github.com/Indyuce/mmocore/wiki/stats.yml), but none of it i can fing in actual config. And they are not appying on enchantment table.

[Items](https://github.com/Indyuce/mmocore/wiki/items.yml) is also outdated.

**Comment by Joshinn-mc** [comment]
Apologies for this, the developer is busy with university and there have been a few inconsistencies with the past few updates. I will try and clean all of that up ASAP. The armor weight and stuff was moved into MMOLib.

**Comment by Darwin1546** [comment]
I saw it in MMOLib, but on 1.1 it disappeared, there is only mitigation now.
Thank you

**Comment by AshenGaming** [comment]
Hi there! We're in the process of cleaning up the Github for MMOCore, and as such closing old issues. If you are still experiencing this issue, please open a new issue using the Issue Template format provided as opposed to re-opening this one.
