### ISSUE TITLE
[Suggestion] Public API

### ISSUE THREAD

**Issue by ThizThizzyDizzy** [mmopluginteam/mmocore#62]
I'm trying to add support for `MMOCore` in my tree feller, to give XP for the blocks mined when trees are felled
The only piece of API I can find is that in the github wiki page ([https://github.com/Indyuce/mmocore/wiki/Plugin-API](https://github.com/Indyuce/mmocore/wiki/Plugin-API))
However, this doesn't provide the functionality I'm looking for, nor is the functionality it does provide well explained
There may be more API, but that's not visible without buying the plugin.

My suggestion is to create a public API containing all methods that can be used by other plugins in order to add compatibility.

**Comment by Joshinn-mc** [comment]
Good suggestion, sorry that the developer is currently busy with school. I will make sure we clean all of these tickets when he is back.

**Comment by Indyuce** [comment]
MMOCore player data is stored in `PlayerData` instances, every player that logs in gets his own instance generated till the server shuts down.

Use `PlayerData.get(player)` to retrieve that instance, then use `PlayerData#giveExperience(int, EXPSource)` to give the player some exp. `PlayerData.giveExperience(int, EXPSource)` lets you display an EXP hologram (if the config option is enabled).

Or use `PlayerData#getCollectionSkills()` which returns a `PlayerProfessions` instance which saves all the profession level/exp data of the player. Methods are pretty self explanatory from there

**Comment by ThizThizzyDizzy** [comment]
What package is the PlayerData class in?
Also, what and where is EXPSource, and how do I use it?

> Methods are self-explanatory from there
Yes, but I can’t see the methods, so I don’t know what methods exist.

I don’t think this is issue deserves to be closed yet
