### ISSUE TITLE
Losing Levels or total wipe of data

### ISSUE THREAD

**Issue by Fortepsai** [mmopluginteam/mmocore#63]
If any of my players do anything 30 min before actual restart all the data upon start up will dissapear for the player, it is very annoying bug and cant even imagine how bad it can go on bigger server above 20 players. Please fix it ASAP it is really critical bug . 
Thank you .

**Comment by AshenGaming** [comment]
Hi there! We're in the process of cleaning up the Github for MMOCore, and as such closing old issues. If you are still experiencing this issue, please open a new issue using the Issue Template format provided as opposed to re-opening this one.
