### ISSUE TITLE
Block Regen NOT working

### ISSUE THREAD

**Issue by NakiriAyamesuki** [mmopluginteam/mmocore#65]
Block Regen NOT working when restart as soon as players breaked block without waiting for block regen.
1.15.2 version , ADVENTURE MODE

**Comment by AshenGaming** [comment]
Hi there! We're in the process of cleaning up the Github for MMOCore, and as such closing old issues. If you are still experiencing this issue, please open a new issue using the Issue Template format provided as opposed to re-opening this one.
