### ISSUE TITLE
[BUG] Broken Attributes for classes

### ISSUE THREAD

**Issue by Dynamite99** [mmopluginteam/mmocore#71]
PvP, Undead Damage, and PvE damage all do not work for classes. This is true also for their damage reduction values

https://pastebin.com/LgixaaHX

**Comment by AshenGaming** [comment]
Hi there! We're in the process of cleaning up the Github for MMOCore, and as such closing old issues. If you are still experiencing this issue, please open a new issue using the Issue Template format provided as opposed to re-opening this one.
