### ISSUE TITLE
Visual bug with % as decimals

### ISSUE THREAD

**Issue by AshenGaming** [mmopluginteam/mmocore#77]
*Raised by **@mmfire118** on Discord.*

**Describe the bug**
The default strength attribute is supposed to give you 1% health per point, but instead it gives me 100% health per point.  I fixed this by changing it to 0.01% but now the /attributes gui is wrong. Is there a way to multiply the placeholder by 100? I've tried a bunch of thing like: (&a+"{total_max_health}*100"&7) but nothing works.

**Server info:**
 - Spigot Build & Version
 - Plugin Version
 - Potential plugins linked to the issue

**Additional context**

**Comment by Indyuce** [comment]
PvP and PvE damage do exist in MMOLib and work with MI items but aren't recognized by MMOCore, will be fixed

**Comment by Indyuce** [comment]
Should be fixed in the latest dev build. You now must use `1%` for 1% and not 0.01% which means MMOCore does the /100 calculation everytime it reads a stat modifier from the config
