### ISSUE TITLE
PvP, PvE, and Undead Damage Attributes for Classes do not work

### ISSUE THREAD

**Issue by Dynamite99** [mmopluginteam/mmocore#78]
When you place pve-damage: pvp-damage as well as undead-damage: into your class attributes, you will get an error in console saying they are unrecognized and do not work. 

1. Go to a class file, add pve-damage: to the attributes
2. Check console for error message pertaining to pve-damage
3. Can also be tested by hitting a mob, pve damage is unchanged. same goes for undead and pvp

https://pastebin.com/LgixaaHX

Paper Build: 1.15.2 #375 
 MMOCore Version 1.4.1

**Comment by Indyuce** [comment]
PvP and PvE damage do exist in MMOLib and MMOItems but indeed aren't recognized by MMOCore, this will be fixed in the next update
