### ISSUE TITLE
/party causing lag spikes

### ISSUE THREAD

**Issue by blek-id** [mmopluginteam/mmocore#79]
**Describe the bug**
When player uses any command related to the /party command (/party accept, etc2), it will cause the server to spike and freeze for a bit.

**To Reproduce**
1. Get a 2-4 player online
2. Have them run /party command, and /party accept and invite
3. Voila, lag spike

**Expected behavior**
The lag spike shouldn't happen at all

**Server info:**
 - PaperSpigot build 375
 - MMOCore 1.4.1
 - Citizens 2.0.27-b2028

**Additional context**
I've been tracking as to what's causing the lag, and here is what I've found.
https://timings.aikar.co/?id=d0fbebe85e894c58883ea3df49156bec
At first I thought that it has to do with citizens, but looking more into it, mmocore is calling something on citizens which causes the lag issue. This is the timings of the server. You could see that the main party command is having a high tick %, and I tried to narrow it down with spark, and I've found this. https://spark.lucko.me/#pXGUlK0rsN
![image](https://user-images.githubusercontent.com/26654664/86515825-09d28080-be46-11ea-983d-ed8d4c1d4e50.png)

**Comment by Indyuce** [comment]
Should be fixed in the latest dev build, player head texture requests were performed on the main server thread that would essentially freeze the server
