### ISSUE TITLE
The mineblock exp-source doesn't allow custom blocks.

### ISSUE THREAD

**Issue by FancyMango** [mmopluginteam/mmocore#84]
**The problem**
I am currently not able to reward the player when they mine specific custom blocks using the MMOITEMS plugin.

**Solution**
Add support to the mineblock exp-source to allow customblock ids.

**Unlikely Alternate Solution**
The only way to get the idea I want working currently; is to add every single block to the restrictions.yml file.

**Further incentive to get this done ASAP**
Hi, my name is Fancy Mango#0420 on the discord, if need be; contact me to get paid for getting this request done asap.

**Comment by ASangarin** [comment]
Already exists
- 'minemiblock{id=1;amount=1-3}'
