### ISSUE TITLE
PAPI placeholders break

### ISSUE THREAD

**Issue by ImRainlog** [mmopluginteam/mmocore#88]
**Describe the bug**
PAPI Placeholders break on /papi reload

**To Reproduce**
/papi reload

**Expected behavior**
not break lul

**Server info:**
 - Paper 365
 - 1.4.2 - SNAPSHOT
 - PlaceholderAPI

**Comment by ASangarin** [comment]
Going to check how the placeholders are handled, but this might be a PAPI issue.
