### ISSUE TITLE
/mmocore admin health/mana/defense give {player} 1/2/100..

### ISSUE THREAD

**Issue by roy0510** [mmopluginteam/mmocore#99]
Could there be that command to be able to give either "**Health, Mana, Defense**" to a player?
**/mmocore admin health/mana/defense give/add {player} 1/2/100..**

**Comment by Ehhthan** [comment]
If you're interested, mmoextended adds this functionality.

**Comment by ASangarin** [comment]
Getting integrated into the main plugin at some point. For now use MMOExtended.
